services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://postgres:postgres@db:5432/postgres
    volumes:
      - .:/app
    # env_file: ${USERPROFILE}/.tokens/.oxalis.env
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    networks:
      - dev_network
  db:
    image: postgres:latest
    container_name: pg_oxalis
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - dev_network
networks:
  dev_network:
    driver: bridge
